/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://ace2rfjg4vapvdvmbeotpwr3ku.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tgps3e5mtjg23jtgseqp7ilkxy",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cognito_identity_pool_id": "eu-west-3:dfde446e-4bce-41b2-a4d8-b6f6a03ea307",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_FroNhyMsJ",
    "aws_user_pools_web_client_id": "bjr7jufp86ojqtkuraj4qn3d1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "blogappcourseappbda587937fdd4928b0de34f21b9c6f9154021-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
